# Generated by Django 4.2.11 on 2024-07-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='news_image', verbose_name='Изображение')),
                ('news_content', models.TextField(null=True, unique=True, verbose_name='Содержимое')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newscategory')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'db_table': 'events',
            },
        ),
    ]
