# Generated by Django 4.2.11 on 2024-07-05 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='news_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='news_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='newscategory',
            old_name='title_name',
            new_name='name',
        ),
    ]
