# Generated by Django 4.2.11 on 2024-07-10 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=10, verbose_name='Номер телефона')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество людей')),
                ('date', models.CharField(max_length=20, verbose_name='Дата заказа')),
                ('time', models.CharField(max_length=10, verbose_name='Время заказа')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Дополнительная информация')),
                ('created_timestemp', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания запроса на резервацию')),
                ('accepted', models.BooleanField(default=False, verbose_name='Обработано')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Зарезервированный стол',
                'verbose_name_plural': 'Зарезервированные столы',
                'db_table': 'reservation',
            },
        ),
    ]
