# Generated by Django 4.2.11 on 2024-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meals_image', verbose_name='Изображение'),
        ),
    ]
